// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoCBbW-wmUlBDZ7dUblzEpsbAJwpYP6rU',
    appId: '1:124474813239:web:684cecb3c489677f5308b2',
    messagingSenderId: '124474813239',
    projectId: 'zenith-af3c4',
    authDomain: 'zenith-af3c4.firebaseapp.com',
    storageBucket: 'zenith-af3c4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvbGbZEbFH4BMoTz653dJ9_iNeB55dHGM',
    appId: '1:124474813239:android:3eca204e20dc674a5308b2',
    messagingSenderId: '124474813239',
    projectId: 'zenith-af3c4',
    storageBucket: 'zenith-af3c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALgXZ6CC5rO5JcbW2RdX2aEHpVHGHzndw',
    appId: '1:124474813239:ios:09cf2dbe69e15c675308b2',
    messagingSenderId: '124474813239',
    projectId: 'zenith-af3c4',
    storageBucket: 'zenith-af3c4.appspot.com',
    iosBundleId: 'com.example.projectZenith',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALgXZ6CC5rO5JcbW2RdX2aEHpVHGHzndw',
    appId: '1:124474813239:ios:b6eac0992ec8a1da5308b2',
    messagingSenderId: '124474813239',
    projectId: 'zenith-af3c4',
    storageBucket: 'zenith-af3c4.appspot.com',
    iosBundleId: 'com.example.projectZenith.RunnerTests',
  );
}
